[package]
name = "init-application"
version = "1.5.0"
edition = "2024"
repository = "https://github.com/GeorgeMunday/init-application"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs-next = "2"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
